### ISSUE TITLE
Travis build wipes sphinx_graphene_theme/__init__.py

### ISSUE THREAD

**Issue by ttz21** [GraphQL-python-archive/old-graphene-python.org#8]
Travis commit 57fd2ba42830c12bdccb5d59e737772f6d6d2635 deleted `__version__` from sphinx_graphene_theme/__init__.py on the `docs` branch (likely due to an error in the `sed` command in .travis.yml)

This means that anyone working on contributing to the graphene docs cannot use the makefiles to build rst files because they will receive the following error:

`ImportError: cannot import name '__version__'`

**Comment by syrusakbary** [comment]
This is now fixed :)
